#pragma config(Motor,  port2,           one,           tmotorNormal, openLoop)
#pragma config(Motor,  port3,           two,           tmotorNormal, openLoop)
#pragma config(Motor,  port4,           three,         tmotorNormal, openLoop)
#pragma config(Motor,  port5,           four,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* The fixSpeed function ensures that the speed applied to the motor is less than 128 and greater than -1 */
int fixSpeed(int speed)
{
  if (speed > 127)
  {
    return 127;
  }
  else if (speed < -127)
  {
    return -127;
  }
  else
  {
    return speed;
  }
}

task main()
{
  while (true)
  {
    // assign the values to some variables, here we take the values
    // of the right joystick, and the horizontal-movement values of the
    // left joystick
    //
    // Therefore, the directional movement controls are on the right joystick
    // and the turning/spinning of the robot is on the left joystick
    int joy_right_x = vexRT[Ch1];
    int joy_right_y = vexRT[Ch2];
    int joy_left_x = vexRT[Ch4];

    // here we calculate the appropriate speed for all of the motors, then we apply them to said motors
    motor[one] = fixSpeed(joy_right_y - joy_right_x - joy_left_x) + 127;
    motor[two] = fixSpeed(-joy_right_y - joy_right_x - joy_left_x) + 127;
    motor[three] = fixSpeed(-joy_right_y - joy_right_x - joy_left_x) + 127;
    motor[four] = fixSpeed(joy_right_y - joy_right_x - joy_left_x) + 127;
    // the formula is the same for motors one and four, and two and three
    // note that the motor numbering system will vary depending on where the motors
    // are positioned on the robot, and what ports the motors are connected to
    // note that this could be changed through the motor configuration menu
  }
}
