#pragma config(Sensor, dgtl1,  quad,                sensorQuadEncoder)
#pragma config(Motor,  port2,           liftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pid.h"

task main()
{
  float Kp = 1;
  float Ki = 0.005;
  float Kd = 0.5;

  int hz = 25;
  int dt = 1000/hz;

  pid_state_t pid_state;
  pid_init_state(pid_state, Kp, Ki, Kd);

  SensorValue[quad] = 0;

  while(true)
  {
    int output = pid(pid_state, SensorValue[quad], dt);
    motor[liftMotor] = 30;

    wait1Msec(dt);
  }
}

#include "pid.c"
